amigos/accounts/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^alterar-dados/$', views.update_user, name='update_user'),
    url(r'^alterar-senha/$', views.update_password, name='update_password'),
    url(r'^registro/$', views.register, name='register'),
    url(r'^perfil/$', views.perfil, name='perfil'),
    url(r'^friend_perfil/(?P<id>\w+)/$', views.friend_perfil, name='friend_perfil'),
]

amigos/amigos/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve as serve_static
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout

from core import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^entrar/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page': 'index'}, name='logout'),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^score/', include('score.urls', namespace='score')),
    url(r'^admin/', admin.site.urls),
    url(r'^oauth2/', views.oauth2, name='oauth2'),
    url(r'^inicio/', views.inicial, name='inicial')
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

amigos/score/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^list$', views.list_friends, name='list'),
    url(r'^addfriend/(?P<id>\w+)$', views.addfriend, name='addfriend'),
    url(r'^accept/(?P<id>\w+)$', views.accept, name='accept'),
    url(r'^friendships$', views.list_solicitations, name='list_solicitations'),
]

amigos/score/models.py
from django.db import models
from accounts.models import User, Match, MatchManager


# Create your models here.

class Friendship(models.Model):
    user_id = models.IntegerField(null=False)
    friend = models.ForeignKey(User, on_delete=models.CASCADE)
    accept = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Friendship"
        verbose_name_plural = "Friendships"

amigos/score/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from accounts.models import Match, User
from .models import Friendship
from django.contrib import messages
from django.shortcuts import redirect
from accounts.models import *

# Create your views here.
@login_required
def list_friends(request):
    matches = Match.objects.calc_points(user=request.user)
    context = {'matches': matches}
    return render(request, 'score/list_friends.html', context)

@login_required
def addfriend(request, id):
    friend = User.objects.get(id=id)
    Friendship.objects.get_or_create(user_id=request.user.id, friend=friend)
    messages.success(request, 'Solicitação enviada com sucesso')
    return redirect('index')

@login_required
def list_solicitations(request):
    list = Friendship.objects.filter(friend=request.user)
    solicitations = []
    user_books = BookUser.objects.filter(user=request.user)
    user_music = MusicUser.objects.filter(user=request.user)
    user_games = GameUser.objects.filter(user=request.user)
    user_videos = VideoUser.objects.filter(user=request.user)
    for solicitation in list:
        itens = []
        match_books = BookUser.objects.filter(user=solicitation.user_id)
        for a in user_books:
            for b in match_books:
                if a.book.id == b.book.id:
                    itens.append(a.book.name)
        
        match_videos = VideoUser.objects.filter(user=solicitation.user_id)
        for a in user_videos:
            for b in match_videos:
                if a.video.id == b.video.id:
                    itens.append(a.video.name)
        
        match_games = GameUser.objects.filter(user=solicitation.user_id)
        for a in user_games:
            for b in match_games:
                if a.game.id == b.game.id:
                    itens.append(a.game.name)
        
        match_music = MusicUser.objects.filter(user=solicitation.user_id)
        for a in user_music:
            for b in match_music:
                if a.music.id == b.music.id:
                    itens.append(a.music.name)
        solicitations.append([User.objects.get(id=solicitation.user_id), " | ".join(itens)])

    context = {'list_friendships': solicitations}
    return render(request, 'score/friendships.html', context)

@login_required
def accept(request, id):
    friendship = Friendship.objects.get(user_id=id, friend=request.user)
    friendship.accept = True
    friendship.save()
    messages.success(request, 'Convite aceito com sucesso')

amigos/score/templates/score/friendships.html
{% extends 'base.html' %}
{% block title %}Solicitations{% endblock %}
{% block content %}
    <header class="parallax" style="background-image: url({{ request.user.cover }});">
        <div class="img-circle">

            <div class="container" style="padding: 100px!important;">
                <a href="{% url 'accounts:perfil' %}">
                    <img src="{{ request.user.picture }}" class="img-circle" alt="Cinque Terre" width="130"
                         height="130"/>
                </a>
            </div>
            </a>
        </div>
    </header>
    <div class="container">
        <h1 style="padding-top: 80px">{{ request.user }}</h1>
    </div>
    {% for friend in list_friendships %}
        <div class="col-md-12 col-sm-12 col-xs-12 profile_details">
            <div class="well profile_view">
                <div class="col-sm-12 col-xs-12">
                    <div class=" col-xs-12 col-md-3 text-center">
                        <img src="{{ friend.0.picture }}" alt="" class="img-circle img-responsive">
                    </div>
                    <div class="right col-xs-9 text-left">
                        <h1>{{ friend.0.name }}</h1>
                        <p><strong>Common: </strong> {{ friend.1 }} </p>
                        <ul class="list-unstyled">
                            <li><i class="fa fa-building"></i> City: Santa Maria</li>
                        </ul>
                    </div>
                </div>

                <div class="col-xs-6 bottom text-left">
                    <div class="text-right col-xs-12 col-sm-12 emphasis ">
                        <a href="{% url 'score:accept' friend.0.id %}">
                            <button type="button" class="btn btn-primary btn-xs">
                                <i class="fa fa-user"> </i> Aceitar
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

amigos/score/templates/score/list_friends.html
{% extends "base.html" %}
{% block title %} Plain Pauge {% endblock title %}
{% block stylesheets %}
    {{ block.super }}
{% endblock stylesheets %}
{% block content %}
    {% load static %}
    <header class="parallax" style="background-image: url({{ request.user.cover }});">
        <div class="img-circle">
            <a href="{% url 'accounts:perfil' %}">
                <div class="container" style="padding: 100px!important;">
                    <a href="{% url 'accounts:perfil' %}">
                        <img src="{{ request.user.picture }}" class="img-circle" alt="Cinque Terre" width="130"
                             height="130"/>
                    </a>
                </div>
        </div>
    </header>
    <div class="container">
        <h1 style="padding-top: 80px">{{ request.user }}</h1>
    </div>
    <div class="card col-sm-6 col-sm-offset-3">
        <div class="card-block">
            <div class="col-md-12">
                <h2 class="card-title" style="margin-bottom: 10px">Seus TOP MATCHES</h2>
                {#card_relação#}
                {% for match in matches %}
                    {% include 'score/match.html' %}
                {% endfor %}
                {#END card_relação#}
            </div>
        </div>
    </div>
{% endblock content %}
{% block javascripts %}
    {{ block.super }}
{% endblock javascripts %}

amigos/score/templates/score/match.html
<div class="col-md-12 col-sm-12 col-xs-12 profile_details">
    <div class="well profile_view">
        <div class="col-sm-12 col-xs-12">
            <div class=" col-xs-12 col-md-3 text-center">
                <img src="{{ match.match.picture }}" alt="" class="img-circle img-responsive">
            </div>
            <div class="right col-xs-9 text-left">
                <h1>{{ match.match.name }}</h1>
                <p><strong>Common: </strong> Localização, Musicas, Livros, Filmes, Comidas </p>
                <ul class="list-unstyled">
                    <li><i class="fa fa-building"></i> City: Santa Maria</li>
                </ul>
            </div>
        </div>
        <div class="col-xs-6 bottom text-right">
            <div class="text-left col-xs-12 col-sm-12 emphasis ">
                <td class="project_progress">
                    <div class="progress progress_sm">
                        <div class="progress-bar bg-green" role="progressbar"
                             data-transitiongoal="57" style="width: {{ match.points }}%;"></div>
                    </div>
                    <small>{{ match.points }}% afinidade</small>
                </td>
            </div>
        </div>
        <div class="col-xs-6 bottom text-left">
            <div class="text-right col-xs-12 col-sm-12 emphasis ">
                <a href="{% url 'accounts:friend_perfil' match.match_id %}">
                    <button type="button" class="btn btn-primary btn-xs">
                        <i class="fa fa-user"> </i> View Profile
                    </button>
                </a>
                <a href="{% url 'score:addfriend' match.match_id %}">
                    <button type="button" class="btn btn-primary btn-xs">
                        <i class="fa fa-user"> </i> Add Friend
                    </button>
                </a>
            </div>
        </div>
    </div>
</div>