amigos/accounts/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^alterar-dados/$', views.update_user, name='update_user'),
    url(r'^alterar-senha/$', views.update_password, name='update_password'),
    url(r'^registro/$', views.register, name='register'),
    url(r'^perfil/$', views.perfil, name='perfil'),
    url(r'^friend_perfil/(?P<id>\w+)/$', views.friend_perfil, name='friend_perfil'),
]

amigos/amigos/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve as serve_static
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout

from core import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^entrar/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page': 'index'}, name='logout'),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^score/', include('score.urls', namespace='score')),
    url(r'^admin/', admin.site.urls),
    url(r'^oauth2/', views.oauth2, name='oauth2'),
    url(r'^inicio/', views.inicial, name='inicial')
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

amigos/score/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^list$', views.list_friends, name='list'),
    url(r'^addfriend/(?P<id>\w+)$', views.addfriend, name='addfriend'),
    url(r'^accept/(?P<id>\w+)$', views.accept, name='accept'),
    url(r'^friendships$', views.list_solicitations, name='list_solicitations'),
]

amigos/accounts/models.py
# coding=utf-8

import re

from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        'Apelido / Usuário', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um nome de usuário válido. '
                'Este valor deve conter apenas letras, números '
                'e os caracteres: @/./+/-/_ .'
                , 'invalid'
            )
        ], help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma'
    )
    name = models.CharField('Nome', max_length=100, blank=True)
    email = models.EmailField('E-mail', unique=True)
    fb_id = models.IntegerField('fb_id', unique=True)
    is_staff = models.BooleanField('Equipe', default=False)
    is_active = models.BooleanField('Ativo', default=True)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)
    link = models.CharField(verbose_name='Link', max_length=300, default='')

    picture = models.CharField(verbose_name='Picture', max_length=300, default='https://openclipart.org/image/2400px/svg_to_png/211821/matt-icons_preferences-desktop-personal.png')
    cover = models.CharField(verbose_name='Cover', max_length=300, default='https://jornalismoespecializadounesp.files.wordpress.com/2014/04/capas-para-facebook-capa-facebook-777366.jpg')
    # Token facebook
    token_api = models.CharField('Token', max_length=300, null=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'
        unique_together = ['id', 'token_api']

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]


class MatchManager(models.Manager):
    def getcreate(self, user, match):
        try:
            match = Match.objects.get(user_id=user.id, match=match)
        except ObjectDoesNotExist:
            match = Match.objects.create(user_id=user.id, match=match)
        return match

    def calc_points(self, user):
        print("[LOG] Calculando afinidades...")
        all_users = User.objects.all()
        user_books = BookUser.objects.filter(user=user)
        user_music = MusicUser.objects.filter(user=user)
        user_games = GameUser.objects.filter(user=user)
        user_videos = VideoUser.objects.filter(user=user)
        for current_user in all_users:
            if current_user.id != user.id:
                match = self.getcreate(user=user, match=current_user)
                match.points = 0
                total_points = 0

                match_books = BookUser.objects.filter(user=current_user)
                total_points += user_books.count()
                for a in user_books:
                    for b in match_books:
                        if a.book.id == b.book.id:
                            match.points += 1
                
                match_videos = VideoUser.objects.filter(user=current_user)
                total_points += user_videos.count()
                for a in user_videos:
                    for b in match_videos:
                        if a.video.id == b.video.id:
                            match.points += 1
                
                match_games = GameUser.objects.filter(user=current_user)
                total_points += user_games.count()
                for a in user_games:
                    for b in match_games:
                        if a.game.id == b.game.id:
                            match.points += 1
                
                match_music = MusicUser.objects.filter(user=current_user)
                total_points += user_music.count()
                for a in user_music:
                    for b in match_music:
                        if a.music.id == b.music.id:
                            match.points += 1
                
                match.points = match.points * 100 // total_points
                match.save()                

        total_matches = Match.objects.filter(user_id=user.id)
        print("[LOG] Afinidades calculadas.")
        return total_matches


# Relacoes entre amigos
class Match(models.Model):
    points = models.IntegerField(default=0)
    user_id = models.IntegerField(null=False)
    match = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Match"
        verbose_name_plural = "Matches"
        ordering = ['-points']
        unique_together = ['user_id', 'match']

    objects = MatchManager()


# Tabelas dos gostos
class Books(models.Model):
    id_api = models.IntegerField(unique=True)
    name = models.CharField('Nome', max_length=300, null=False)

    def __str__(self):
        return self.name


class Games(models.Model):
    id_api = models.IntegerField(unique=True)
    name = models.CharField('Nome', max_length=300, null=False)
    def __str__(self):
        return self.name

class Musics(models.Model):
    id_api = models.IntegerField(unique=True)
    name = models.CharField('Nome', max_length=300, null=False)
    def __str__(self):
        return self.name

class Videos(models.Model):
    id_api = models.IntegerField(unique=True)
    name = models.CharField('Nome', max_length=300, null=False)
    def __str__(self):
        return self.name

# Relações NxN
class VideoUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    video = models.ForeignKey(Videos, on_delete=models.CASCADE)


class GameUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Games, on_delete=models.CASCADE)


class BookUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Books, on_delete=models.CASCADE)

class MusicUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    music = models.ForeignKey(Musics, on_delete=models.CASCADE)

amigos/accounts/forms.py
# coding=utf-8

from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import User


class UserAdminCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email']


class UserAdminForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name', 'is_active', 'is_staff']

amigos/accounts/views.py
# coding=utf-8
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.generic import (TemplateView, UpdateView, FormView)
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm
from .models import User
from .forms import UserAdminCreationForm
from django.contrib import messages
from accounts.models import BookUser, GameUser, VideoUser, MusicUser


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/index.html'


def perfil(request):
    books = []
    games = []
    videos = []
    musics = []
    for i in BookUser.objects.filter(user=request.user):
        n = BookUser.objects.filter(book_id=i.id).count()
        books.append([i.book, n-1])
    for i in GameUser.objects.filter(user=request.user):
        n = GameUser.objects.filter(game_id=i.id).count()
        games.append([i.game,n-1])
    for i in VideoUser.objects.filter(user=request.user):
        n = VideoUser.objects.filter(video_id=i.id).count()
        videos.append([i.video,n-1])
    for i in MusicUser.objects.filter(user=request.user):
        n = MusicUser.objects.filter(music_id=i.id).count()
        musics.append([i.music,n-1])
    return render(request, 'accounts/perfil/perfil.html', {'books': books,'games': games,'videos':videos,'musics':musics})


def friend_perfil(request, id):
    user = User.objects.get(id=id)
    books = []
    games = []
    videos = []
    musics = []
    for i in BookUser.objects.filter(user=user):
        n = BookUser.objects.filter(book_id=i.id).count()
        books.append([i.book, n - 1])
    for i in GameUser.objects.filter(user=user):
        n = GameUser.objects.filter(game_id=i.id).count()
        games.append([i.game, n - 1])
    for i in VideoUser.objects.filter(user=user):
        n = VideoUser.objects.filter(video_id=i.id).count()
        videos.append([i.video, n - 1])
    for i in MusicUser.objects.filter(user=user):
        n = MusicUser.objects.filter(music_id=i.id).count()
        musics.append([i.music, n - 1])
    return render(request, 'accounts/perfil/perfil.html',
                  {'books': books, 'games': games, 'videos': videos, 'musics': musics, 'user': user})


def register(request):
    form = UserAdminCreationForm()
    if request.method == 'POST':
        form = UserAdminCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Conta criada com sucesso')
            return redirect('login')
    return render(request, 'accounts/register.html', {'form': form})


class UpdateUserView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'accounts/update_user.html'
    fields = ['name', 'email']
    success_url = reverse_lazy('accounts:index')

    def get_object(self):
        return self.request.user


class UpdatePasswordView(LoginRequiredMixin, FormView):
    template_name = 'accounts/update_password.html'
    success_url = reverse_lazy('accounts:index')
    form_class = PasswordChangeForm

    def get_form_kwargs(self):
        kwargs = super(UpdatePasswordView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(UpdatePasswordView, self).form_valid(form)


index = IndexView.as_view()
update_user = UpdateUserView.as_view()
update_password = UpdatePasswordView.as_view()

amigos/accounts/templates/accounts/index.html
{% extends "base.html" %}

{% block title %}Minha Conta{% endblock %}

{% block titulo %} Minha Conta {% endblock %}
{% block content %}
            <!-- CONTENT -->
            <ol class="breadcrumb">
                <li><a href="{% url 'accounts:index' %}">Início</a></li>
                <li class="active">Minha Conta</li>
            </ol>
            <div class="row">
                <div class="col-md-4">
                    <div class="list-group">
                        <a href="{% url 'accounts:index' %}" class="list-group-item active">Minha
                            Conta</a>
                        <a href="{% url 'accounts:update_user' %}" class="list-group-item">Alterar
                            Dados</a>
                        <a href="{% url 'accounts:update_password' %}" class="list-group-item">Alterar
                            Senha</a>
                    </div>
                </div>
                <div class="col-md-8">
                    {% block accounts_container %}
                        <h2>Bem vindo {{ user }}</h2>
                    {% endblock %}
                </div>
            </div>
            <!-- ENDCONTENT -->
{% endblock %}

amigos/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}{{ block.super }} Entrar {% endblock %}
{% block body_class %}login{% endblock body_class %}
{% block body %}
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <div style="height: 100%;background: url('{% static 'build/images/ini.jpg'%}');background-position: center center;">

        <div class="login-page">
            <div class="text-center" style="position: absolute">
                <h1 style="font-size: 58px; color: #111">Aproximando <strong>interesses</strong>...<br/>
                Criando <strong> Amizades</strong></h1>
            </div>
            <div class="form" style="top: 210px;">
                <h1>SIMILAR's</h1>
                <br/>
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
                <form class="login-form" action="{% url 'oauth2' %}">
                    <button>ENTRAR COM FACEBOOK <i class="fa fa-facebook-official" style="color: #fff"></i></button>
                </form>
            </div>
        </div>
    </div>
    <style>

    @import url(https://fonts.googleapis.com/css?family=Pacifico);
    /* latin-ext */
@font-face h1 {
  font-family: 'Pacifico';
  font-style: normal;
  font-weight: 400;
  src: local('Pacifico Regular'), local('Pacifico-Regular'), url(https://fonts.gstatic.com/s/pacifico/v12/6RfRbOG3yn4TnWVTc898ERTbgVql8nDJpwnrE27mub0.woff2) format('woff2');
  unicode-range: U+0100-024F, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF, U+2C60-2C7F, U+A720-A7FF;
}

.login-page {
  width: 360px;
  padding: 8% 0 0;
  margin: auto;
}
.form {
  margin: 20px;
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
{#  margin: 0 auto 100px;#}
  padding: 45px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}
.form input {
  font-family: "Roboto", sans-serif;
  outline: 0;
  background: #f2f2f2;
  width: 100%;
  border: 0;
  margin: 0 0 15px;
  padding: 15px;
  box-sizing: border-box;
  font-size: 14px;
}
.form button {
  font-family: "Roboto", sans-serif;
  text-transform: uppercase;
  outline: 0;
  background: #5C6BC0;
  width: 100%;
  border: 0;
  padding: 15px;
  color: #FFFFFF;
  font-size: 14px;
  -webkit-transition: all 0.3 ease;
  transition: all 0.3 ease;
  cursor: pointer;
}
.form button:hover,.form button:active,.form button:focus {
  background: #1A237E;
}
.form .message {
  margin: 15px 0 0;
  color: #b3b3b3;
  font-size: 12px;
}
.form .message a {
  color: #4CAF50;
  text-decoration: none;
}
.form .register-form {
  display: none;
}
.container {
  position: relative;
  z-index: 1;
  max-width: 300px;
  margin: 0 auto;
}
.container:before, .container:after {
  content: "";
  display: block;
  clear: both;
}
.container .info {
  margin: 50px auto;
  text-align: center;
}
.container .info h1 {
  margin: 0 0 15px;
  padding: 0;
  font-size: 36px;
  font-weight: 300;
  color: #1a1a1a;
}
.container .info span {
  color: #4d4d4d;
  font-size: 12px;
}
.container .info span a {
  color: #000000;
  text-decoration: none;
}
.container .info span .fa {
  color: #EF3B3A;
}
body {
  background: #5283b8; /* fallback for old browsers */
  font-family: "Roboto", sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
    </style>
{% endblock body %}

amigos/accounts/templates/accounts/update_password.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}

{% block title %}Alterar Senha{% endblock %}

{% block accounts_container %}
    <h2>Alterar Senha</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

amigos/accounts/templates/accounts/update_user.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}

{% block title %}Alterar Dados{% endblock %}

{% block accounts_container %}
    <h2>Alterar Dados</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}