amigos/amigos/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve as serve_static
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout

from core import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^entrar/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page': 'index'}, name='logout'),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^score/', include('score.urls', namespace='score')),
    url(r'^admin/', admin.site.urls),
    url(r'^oauth2/', views.oauth2, name='oauth2'),
    url(r'^inicio/', views.inicial, name='inicial')
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

amigos/score/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^list$', views.list_friends, name='list'),
    url(r'^addfriend/(?P<id>\w+)$', views.addfriend, name='addfriend'),
    url(r'^accept/(?P<id>\w+)$', views.accept, name='accept'),
    url(r'^friendships$', views.list_solicitations, name='list_solicitations'),
]

amigos/core/models.py
from django.db import models
from accounts.models import User
# Create your models here.

amigos/core/forms.py
# coding=utf-8

from django import forms
from django.core.mail import send_mail
from django.conf import settings

amigos/core/views.py
# coding=utf-8
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from accounts.models import User
from django.http import HttpResponseRedirect, HttpResponse
import requests
from core import facebook
from core import user_config
from django.contrib.auth import login
import json

class IndexView(LoginRequiredMixin, TemplateView):
    model = User
    template_name = 'index.html'

index = IndexView.as_view()

def inicial(request):
    user = User.objects.all()
    print('oi')
    for u in user:
        print(u.name)

    return render(request, 'inicial.html')

def oauth2(request):
    if request.GET.get('code'):
        code = request.GET['code']
        dic = facebook.get_token('http://localhost:8000/oauth2/', code)
        token = dic['access_token']
        user_config.checkUser(token)
        user = User.objects.get(token_api=token)
        login(request, user)
        return redirect('index')
    else:
        return HttpResponseRedirect(facebook.url_to_login('http://localhost:8000/oauth2/'))

def index(request):
    return redirect('score/list')

amigos/core/templates/partial/footer.html
<div class="pull-right">
    FREEnd -developed by <a
        href="https://colorlib.com/wp/free-bootstrap-admin-dashboard-templates/">Chuhaskel</a>
</div>
<div class="clearfix"></div>

amigos/core/templates/partial/header.html
{% load static %}
 <!-- ######################GENTELLA######################### -->
    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- bootstrap-daterangepicker -->
    <link href="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{% static 'vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">
    <!-- bootstrap-progressbar -->
    <link href="{% static 'vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}"
          rel="stylesheet">
    <!-- JQVMap -->
    <link href="{% static 'vendors/jqvmap/dist/jqvmap.min.css' %}" rel="stylesheet"/>

 <!-- ######################upgrade gentella######################### -->
    <link href='http://fonts.googleapis.com/css?family=Droid+Serif|Open+Sans:400,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="{% static 'build/css/reset.css' %}"> <!-- CSS reset -->
	<link rel="stylesheet" href="{% static 'build/css/style.css'%}">
	<link rel="stylesheet" href="{% static 'build/css/bootstrap-theme.css'%}"> <!-- CSS reset -->
	<link rel="stylesheet" href="{% static 'build/css/bootstrap.css'%}"> <!-- CSS reset -->
	<link rel="stylesheet" href="{% static 'build/css/style2.css'%}"> <!-- Resource style -->

amigos/core/templates/partial/scripts.html
{% load static %}
    <!-- ######################GENTELLA######################### -->
    <!-- jQuery -->
    <script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
    <!-- NProgress -->
    <script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
    <!-- bootstrap-progressbar -->
    <script src="{% static 'vendors/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
    <!-- iCheck -->
    <script src="{% static 'vendors/iCheck/icheck.min.js' %}"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
    <!-- bootstrap-wysiwyg -->
    <script src="{% static 'vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js' %}"></script>
    <script src="{% static 'vendors/jquery.hotkeys/jquery.hotkeys.js' %}"></script>
    <script src="{% static 'vendors/google-code-prettify/src/prettify.js' %}"></script>
    <!-- jQuery Tags Input -->
    <script src="{% static 'vendors/jquery.tagsinput/src/jquery.tagsinput.js' %}"></script>
    <!-- Switchery -->
    <script src="{% static 'vendors/switchery/dist/switchery.min.js' %}"></script>
    <!-- Select2 -->
    <script src="{% static 'vendors/select2/dist/js/select2.full.min.js' %}"></script>
    <!-- Parsley -->
    <script src="{% static 'vendors/parsleyjs/dist/parsley.min.js' %}"></script>
    <!-- Autosize -->
    <script src="{% static 'vendors/autosize/dist/autosize.min.js' %}"></script>
    <!-- jQuery autocomplete -->
    <script src="{% static 'vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js' %}"></script>
    <!-- starrr -->
    <script src="{% static 'vendors/starrr/dist/starrr.js' %}"></script>
    <!-- ######################upgrade gentella######################### -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

amigos/core/templates/partial/sidebar.html
<div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
        <a href="{% url 'index' %}" class="site_title"><i class="fa fa-spinner"></i> <span>Gentelella Alela!</span></a>
    </div>

    <div class="clearfix"></div>

    <!-- menu profile quick info -->
    <div class="profile clearfix">
        <div class="profile_pic">
            <img src="/static/images/img.jpg" alt="..." class="img-circle profile_img">
        </div>
        <div class="profile_info">
            <span>Welcome,</span>
            <h2>John Doe</h2>
        </div>
    </div>
    <!-- /menu profile quick info -->

    <br/>

    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
        <div class="menu_section">
            <h3>General</h3>
            <ul class="nav side-menu">
                <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="index.html">Dashboard</a></li>
                        <li><a href="index2.html">Dashboard2</a></li>
                        <li><a href="index3.html">Dashboard3</a></li>
                    </ul>
                </li>
                <li><a><i class="fa fa-edit"></i> Forms <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="form.html">General Form</a></li>
                        <li><a href="form_advanced.html">Advanced Components</a></li>
                        <li><a href="form_validation.html">Form Validation</a></li>
                        <li><a href="form_wizards.html">Form Wizard</a></li>
                        <li><a href="form_upload.html">Form Upload</a></li>
                        <li><a href="form_buttons.html">Form Buttons</a></li>
                    </ul>
                </li>
                <li><a><i class="fa fa-desktop"></i> UI Elements <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="general_elements.html">General Elements</a></li>
                        <li><a href="media_gallery.html">Media Gallery</a></li>
                        <li><a href="typography.html">Typography</a></li>
                        <li><a href="icons.html">Icons</a></li>
                        <li><a href="glyphicons.html">Glyphicons</a></li>
                        <li><a href="widgets.html">Widgets</a></li>
                        <li><a href="invoice.html">Invoice</a></li>
                        <li><a href="inbox.html">Inbox</a></li>
                        <li><a href="calendar.html">Calendar</a></li>
                    </ul>
                </li>
                <li><a><i class="fa fa-table"></i> Tables <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="tables.html">Tables</a></li>
                        <li><a href="tables_dynamic.html">Table Dynamic</a></li>
                    </ul>
                </li>
                <li><a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="chartjs.html">Chart JS</a></li>
                        <li><a href="chartjs2.html">Chart JS2</a></li>
                        <li><a href="morisjs.html">Moris JS</a></li>
                        <li><a href="echarts.html">ECharts</a></li>
                        <li><a href="other_charts.html">Other Charts</a></li>
                    </ul>
                </li>
                <li><a><i class="fa fa-clone"></i>Layouts <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="fixed_sidebar.html">Fixed Sidebar</a></li>
                        <li><a href="fixed_footer.html">Fixed Footer</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="menu_section">
            <h3>Live On</h3>
            <ul class="nav side-menu">
                <li><a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="e_commerce.html">E-commerce</a></li>
                        <li><a href="projects.html">Projects</a></li>
                        <li><a href="project_detail.html">Project Detail</a></li>
                        <li><a href="contacts.html">Contacts</a></li>
                        <li><a href="profile.html">Profile</a></li>
                    </ul>
                </li>
                <li><a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="page_403.html">403 Error</a></li>
                        <li><a href="page_404.html">404 Error</a></li>
                        <li><a href="page_500.html">500 Error</a></li>
                        <li><a href="plain_page.html">Plain Page</a></li>
                        <li><a href="login.html">Login Page</a></li>
                        <li><a href="pricing_tables.html">Pricing Tables</a></li>
                    </ul>
                </li>
                <li><a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="#level1_1">Level One</a>
                        <li><a>Level One<span class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu">
                                <li class="sub_menu"><a href="level2.html">Level Two</a>
                                </li>
                                <li><a href="#level2_1">Level Two</a>
                                </li>
                                <li><a href="#level2_2">Level Two</a>
                                </li>
                            </ul>
                        </li>
                        <li><a href="#level1_2">Level One</a>
                        </li>
                    </ul>
                </li>
                <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span
                        class="label label-success pull-right">Coming Soon</span></a></li>
            </ul>
        </div>
    </div>
    <!-- /sidebar menu -->

    <!-- /menu footer buttons -->
    <div class="sidebar-footer hidden-small">
        <a data-toggle="tooltip" data-placement="top" title="Settings">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Lock">
            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Logout" href="{% url 'logout' %}">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
        </a>
    </div>
    <!-- /menu footer buttons -->
</div>

amigos/core/templates/partial/top_navegation.html
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
<div class="container">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
		<i class="fa fa-bars"></i>
		</button>
		<a class="navbar-brand page-scroll" href="{% url 'score:list' %}">
		HOME </a>
        <a class="navbar-brand page-scroll" href="{% url 'score:list_solicitations' %}">
		SOLICITAÇÕES </a>
        <a class="navbar-brand page-scroll" href="{% url 'logout' %}">
		LOGOUT </a>
        </a>
	</div>
	<!-- Collect the nav links, forms, and other content for toggling -->
	<!-- /.navbar-collapse -->
</div>
<!-- /.container -->

{#<div class="nav_menu">#}
{#    <nav>#}
{#        <div class="nav toggle">#}
{#            <a id="menu_toggle"><i class="fa fa-bars"></i></a>#}
{#        </div>#}
{#        <ul class="nav navbar-nav navbar-left">#}
{#            <a href="{% if VOLTAR_URL %}{{ VOLTAR_URL }}{% else %}javascript:history.go(-1){% endif %}">#}
{#                <i class="fa fa-arrow-circle-left grow" aria-hidden="true"></i>#}
{#                Voltar#}
{#            </a>#}
{#        </ul>#}
{#        <ul class="nav navbar-nav navbar-right">#}
{#            <li class="">#}
{#                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"#}
{#                   aria-expanded="false">#}
{#                    <img src="/static/images/img.jpg" alt="">John Doe#}
{#                    <span class=" fa fa-angle-down"></span>#}
{#                </a>#}
{#                <ul class="dropdown-menu dropdown-usermenu pull-right">#}
{#                    <li><a href="{% url 'accounts:index' %}"> Conta</a></li>#}
{#                    <li>#}
{#                        <a href="{% url 'accounts:index' %}">#}
{#                            <span class="badge bg-red pull-right">50%</span>#}
{#                            <span>Settings</span>#}
{#                        </a>#}
{#                    </li>#}
{#                    <li><a href="javascript:;">Help</a></li>#}
{#                    <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out pull-right"></i>Sair</a></li>#}
{#                </ul>#}
{#            </li>#}
{##}
{#            <li role="presentation" class="dropdown">#}
{#                <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">#}
{#                    <i class="fa fa-envelope-o"></i>#}
{#                    <span class="badge bg-green">6</span>#}
{#                </a>#}
{#                <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">#}
{#                    <li>#}
{#                        <a>#}
{#                            <span class="image"><img src="/static/images/img.jpg" alt="Profile Image"/></span>#}
{#                            <span>#}
{#                <span>John Doe</span>#}
{#                <span class="time">3 mins ago</span>#}
{#              </span>#}
{#                            <span class="message">#}
{#                Film festivals used to be do-or-die moments for movie makers. They were where...#}
{#              </span>#}
{#                        </a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a>#}
{#                            <span class="image"><img src="/static/images/img.jpg" alt="Profile Image"/></span>#}
{#                            <span>#}
{#                <span>John Doe</span>#}
{#                <span class="time">3 mins ago</span>#}
{#              </span>#}
{#                            <span class="message">#}
{#                Film festivals used to be do-or-die moments for movie makers. They were where...#}
{#              </span>#}
{#                        </a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a>#}
{#                            <span class="image"><img src="/static/images/img.jpg" alt="Profile Image"/></span>#}
{#                            <span>#}
{#                <span>John Doe</span>#}
{#                <span class="time">3 mins ago</span>#}
{#              </span>#}
{#                            <span class="message">#}
{#                Film festivals used to be do-or-die moments for movie makers. They were where...#}
{#              </span>#}
{#                        </a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a>#}
{#                            <span class="image"><img src="/static/images/img.jpg" alt="Profile Image"/></span>#}
{#                            <span>#}
{#                <span>John Doe</span>#}
{#                <span class="time">3 mins ago</span>#}
{#              </span>#}
{#                            <span class="message">#}
{#                Film festivals used to be do-or-die moments for movie makers. They were where...#}
{#              </span>#}
{#                        </a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <div class="text-center">#}
{#                            <a>#}
{#                                <strong>See All Alerts</strong>#}
{#                                <i class="fa fa-angle-right"></i>#}
{#                            </a>#}
{#                        </div>#}
{#                    </li>#}
{#                </ul>#}
{#            </li>#}
{#        </ul>#}
{#    </nav>#}
{#</div>#}